export const sample_promts: any[] = [
  {
    id:'1',
    name: 'Advanced-Brainstorming',
    description : 'It’s easy to ask ChatGPT to generate a list of ideas for your next  project. But often they’re generic and lack authority. Instead, ask it to come up with new ideas or approaches on a familiar topic.',    
    template : 'Topic: {How to be study more effectively.} For the topic above, brainstorm new ideas or approaches. Prioritize ideas that are uncommon or novel.',
    favorite: false,
    origins: ['alexanderfyoung.com'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['ChatGPT', 'Advanced'],
  },
  {
    id:'2',
    name: 'Get Hyper-Specific',
    description : 'The more specific your prompt the better more specific ChatGPT’s response will be. Use colons to prime ChatGPT with as much information as possible. Niche down and avoid generic response like everyone else.',
    template : 'Topic: How to create an online course For audience: Coaches with social followings of 10,000+ Content goal: Explain how to plan a course, record video course content and how to market a course Writing style: Clear, concise, conversational, logical', 
    favorite: false,
    origins: ['alexanderfyoung.com'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['ChatGPT', 'Advanced'],
  }
]

export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];

